### ISSUE TITLE
Self-signed root certificate causes failure

### ISSUE THREAD

**Issue by jsha** [hiviah/https-everywhere-checker#11]
Some HTTPS sites include the self-signed root cert in the certificate chain they provide. This is always useless: that root cert is either in the trust store or not, and including it doesn't help prove the identity of the site. However, it's harmless except for wasted bytes and browsers don't treat it as an error.

Fetching such a site with the checker produces an error, though:

```
cd https-everywhere
./fetch-test.sh src/chrome/content/rules/Matt_Wilcox.net.xml
...
ERROR src/chrome/content/rules/Matt_Wilcox.net.xml: Fetch error: http://www.mattwilcox.net/ => https://www.mattwilcox.net/: (60, 'SSL certificate problem: self signed certificate in certificate chain')

openssl s_client -connect www.mattwilcox.net:443 -showcerts | grep '[si]:'
...
 3 s:/C=IL/O=StartCom Ltd./CN=StartCom Certification Authority G2
   i:/C=IL/O=StartCom Ltd./CN=StartCom Certification Authority G2
```

Fetching with command-line curl works fine, surprisingly:

```
$ curl -I https://mattwilcox.net
HTTP/1.1 200 OK
```
```

**Comment by hiviah** [comment]
I can't reproduce this. I guess it is a bug of the underlying TLS library (RFC 5246 and older TLS RFCs allow root cert to be included or omitted).

**Comment by jsha** [comment]
I'm using openssl. Are you using gnutls?

**Comment by hiviah** [comment]
Yes, the pycurl I was testing with was linked to gnutls.
