### ISSUE TITLE
String formatting not working properly.

### ISSUE THREAD

**Issue by krngrvr09** [hiviah/https-everywhere-checker#16]
![rsz_error1 1](https://cloud.githubusercontent.com/assets/5905966/7076695/c5f619dc-df28-11e4-96ec-082be444a297.png)

``ERROR %(filename)s: Not enough tests (%(actual_count)d vs %(needed_count)d) for %(rule)s``

One possible solution is to replace ``.format(problem)`` with ``%problem``. So that 

``logging.error("%(filename)s: Not enough tests (%(actual_count)d vs %(needed_count)d) for %(exclusion)s".format(problem))``

becomes

``logging.error("%(filename)s: Not enough tests (%(actual_count)d vs %(needed_count)d) for %(exclusion)s"%problem)``

![rsz_1corrected](https://cloud.githubusercontent.com/assets/5905966/7076726/f6ce9750-df28-11e4-8643-08edc69fa6f7.png)

**Comment by krngrvr09** [comment]
I have tested this on python ``2.7.5+`` and also on ``3.3.2+`` Can anybody confirm that they are also facing the same issue on their machine.

**Comment by hiviah** [comment]
Fixed and pushed to master. Thanks.
