### ISSUE TITLE
License and fork sync

### ISSUE THREAD

**Issue by jayvdb** [hiviah/https-everywhere-checker#21]
As you are no doubt aware, there is a lively fork at https://github.com/EFForg/https-everywhere/tree/master/test/rules , but it is not installable as they have deleted the `__init__.py`.

They found a license problem  https://github.com/EFForg/https-everywhere/issues/6466 and I have raised https://github.com/stricaud/gvgen/issues/11 to see if it can be solved properly.

EFF is using the same license, so it should be fine to pull their changes back into this repo.  If you dont intend to maintain this, maybe we can fix the EFF fork to be installable and ask them to publish a new version periodically, perhaps using a new name.

**Comment by hiviah** [comment]
I have no problem if you want to keep the code live, I haven't touched in a quite some time.

I marked this repo as obsolete with link to https://github.com/EFForg/https-everywhere/tree/master/test/rules as the successor.

IIRC the gvgen code is not necessary requirement for functioning, it was just a tool for debugging the rulesets.

Also you can change the license to GPL-2 or later or what actually suits you (from what I read the author of gvgen agreed to the same resolution).

**Comment by stricaud** [comment]
I just changed the license to MIT and pushed a Pypi package.
