### ISSUE TITLE
PEP8 cleanup

### ISSUE THREAD

**Issue by Thorsten-Sick** [hiviah/https-everywhere-checker#5]
Hi

My IDE complains about some PEP8 issues (especially TABs). If you want I can fix these PEP8 issues and replace the Tabs with spaces and create a PR. What do you think ?
It would make my IDE happy....

**Comment by hiviah** [comment]
PEP8 allows tabs if they are consistently used everywhere. Sorry, but the retab would make just one huge whitespace-only diff.
