### ISSUE TITLE
Checker incorrectly reports missing Location for bitmex.com

### ISSUE THREAD

**Issue by jsha** [hiviah/https-everywhere-checker#9]
Steps to reproduce:

1. Check out https-everywhere repo and init submodules
2. exec python2.7 https-everywhere-checker/src/https_everywhere_checker/check_rules.py https-everywhere-checker/manual.checker.config src/chrome/content/rules/BitMEX.com.xml

Expected results:

Success

Actual results:

ERROR src/chrome/content/rules/BitMEX.com.xml: Fetch error: http://bitmex.com/ => https://bitmex.com/: Redirect for 'https://bitmex.com/' missing Location

Fetch both the HTTP and HTTPS version with the curl command line tool shows Location headers at each hop of both.

**Comment by hiviah** [comment]
I can't reproduce this, in my case the redirect is followed without complaint about missing location header.

DEBUG Following redirect http://www.bitmex.com/ => https://www.bitmex.com/
DEBUG Following redirect https://www.bitmex.com/ => https://www.bitmex.com/app

**Comment by Hainish** [comment]
This is no longer occurring.  I've opened a PR to re-enable BitMEX.com.xml: https://github.com/EFForg/https-everywhere/pull/4475  Please close @jsha or @hiviah
